##############################################################
# Automatically generated by qmake Fri Oct 19 09:35:44 2001
##############################################################

TEMPLATE = app
CONFIG += debug warn_on thread

# Input
HEADERS += BackwardClock.h
SOURCES += BackwardClock.cpp main.cpp
